modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
issueTrackerURL="https://github.com/GeradesoLukas/weaponleveling/issues"

[[mods]]
modId = "weaponleveling"
version = "${version}"
displayName = "Lukas' Weapon Leveling"
authors = "GeradesoLukas"
displayURL="https://www.curseforge.com/minecraft/mc-mods/weapon-leveling"
description = '''
Leveling your items since 2022.
Very customizable mod to make your equipment stronger over time.
'''
logoFile = "assets/weaponleveling/icon.png"

[[dependencies.weaponleveling]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.weaponleveling]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.weaponleveling]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"