modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
issueTrackerURL= "https://github.com/GekidoLukas/weaponleveling/issues"

[[mods]]
modId = "weaponleveling"
version = "${version}"
logoFile = "banner.png"
displayName = "Lukas' Weapon Leveling"
authors = "GekidoLukas"
displayURL="https://www.gekidolukas.com"
description = '''
Leveling your items since 2022.
Very customizable mod to make your equipment stronger over time.

Issues: https://github.com/GekidoLukas/weaponleveling/issues
'''

[[dependencies.weaponleveling]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.weaponleveling]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.weaponleveling]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
[modproperties.weaponleveling]
catalogueImageIcon = "icon.png"
catalogueBackground = "background.png"
